2024-02-02 10:07:52 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, worker_address='http://localhost:40000', controller_address='http://localhost:10000', model_path='./WEIGHTS/ferret-13b-v1.3', model_base=None, model_name=None, multi_modal=False, keep_aspect_ratio=False, num_gpus=1, limit_model_concurrency=5, stream_interval=1, no_register=False, load_8bit=True, load_4bit=False, add_region_feature=False, image_w=336, image_h=336)
2024-02-02 10:07:52 | INFO | model_worker | Loading the model ferret-13b-v1.3 on worker 18e4f4 ...
2024-02-02 10:07:52 | ERROR | stderr | Traceback (most recent call last):
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/miniconda3/envs/ferret/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-02-02 10:07:52 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/miniconda3/envs/ferret/lib/python3.10/runpy.py", line 86, in _run_code
2024-02-02 10:07:52 | ERROR | stderr |     exec(code, run_globals)
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/Desktop/PathGuidedVQA_Base/PathGuidedVQA/ferret/serve/model_worker.py", line 353, in <module>
2024-02-02 10:07:52 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/Desktop/PathGuidedVQA_Base/PathGuidedVQA/ferret/serve/model_worker.py", line 80, in __init__
2024-02-02 10:07:52 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/Desktop/PathGuidedVQA_Base/PathGuidedVQA/ferret/model/builder.py", line 87, in load_pretrained_model
2024-02-02 10:07:52 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/miniconda3/envs/ferret/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 622, in from_pretrained
2024-02-02 10:07:52 | ERROR | stderr |     tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/miniconda3/envs/ferret/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 466, in get_tokenizer_config
2024-02-02 10:07:52 | ERROR | stderr |     resolved_config_file = cached_file(
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/miniconda3/envs/ferret/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
2024-02-02 10:07:52 | ERROR | stderr |     resolved_file = hf_hub_download(
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/miniconda3/envs/ferret/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
2024-02-02 10:07:52 | ERROR | stderr |     validate_repo_id(arg_value)
2024-02-02 10:07:52 | ERROR | stderr |   File "/home/yochin/miniconda3/envs/ferret/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
2024-02-02 10:07:52 | ERROR | stderr |     raise HFValidationError(
2024-02-02 10:07:52 | ERROR | stderr | huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './WEIGHTS/ferret-13b-v1.3'. Use `repo_type` argument if needed.
